on: 
  #push:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Person to say goodbye'
        default: 'World'
        required: true

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say goodbye
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: Zolaton/hello-world-composite-run-steps-action@main
        with:
          who-to-greet: "${{ github.event.inputs.who-to-greet }}"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash